#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
#Autostart
picom &
#killall variety &
#variety &
feh --bg-fill -randomize ~/Pictures/wallpaper/ * 
nm-applet &
pamac-tray &
xfce4-power-manager &
blueberry-tray &
#volumeicon &
$HOME/.config/polybar/launch.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
bspc monitor -d I II III IV V 

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Gimp desktop='^4' state=gapless_monocle follow=on
bspc rule -a zoom desktop='^5' state=floating 
bspc rule -a vivaldi-stable desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a virtualbox desktop='^3' follow=on
bspc rule -a rofi state=floating
