#! /bin/sh
wmname compiz
# export _JAVA_AWT_WM_NONREPARENTING=1
pgrep -x sxhkd > /dev/null || sxhkd &
#Autostart
# picom &
exec --no-startup-id xfsettingsd &
#killall variety &
# variety &
nitrogen --restore &
#feh --bg-fill -randomize ~/Pictures/wallpaper/ * 
nm-applet &
# pamac-tray &
# xfce4-power-manager &
# blueberry-tray &
flameshot &
#volumeicon &
$HOME/.config/polybar/launch.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
bspc monitor eDP -d I II III IV V 
# bspc monitor HDMI-A-0 -d I II III IV V 
# for side in top right bottom left; do bspc config ${side}_monocle_padding -10; done
# Remove top padding in monocle mode
for side in top ; do bspc config ${side}_monocle_padding 0; done
bspc config border_width        4
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#ff79c6"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc rule -a Zathura state=gapless_monocle 
bspc rule -a Gimp desktop='^4' state=gapless_monocle follow=on
bspc rule -a zoom desktop='^5' state=floating 
# bspc rule -a vivaldi-stable desktop='^2' 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a virtualbox desktop='^3' follow=on
bspc rule -a rofi state=floating
bspc rule -a teams desktop='^5' state=floating
bspc rule -a obs desktop='^5' follow=on
