#! /bin/bash
bspc rule -r "*"
MONITOR_NAME="eDP"
EXTERNAL_MONITOR_NAME="HDMI-A-0"
STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
    /home/$USER/.local/bin/second-activate
    nitrogen --restore --head=1&
    notify-send "Second monitor attached!"
else
    second-deactivate
    notify-send "Second monitor deattached!"
fi
wmname compiz
export _JAVA_AWT_WM_NONREPARENTING=1
# pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
#Autostart
picom --experimental-backends &
exec --no-startup-id xsettingsd &
#killall variety &
# variety &
nitrogen --restore --head=0&
#feh --bg-fill -randomize ~/Pictures/wallpaper/ * 
nm-applet &
# pamac-tray &
# xfce4-power-manager &
# blueberry-tray &
flameshot &
#volumeicon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
#Set according to presence of external monitor
if [[ ! $STATUS_EXTERNAL_MONITOR == *disconnected* ]]; then
	bspc monitor $MONITOR_NAME -d 1 2 3 4 5
	bspc monitor $EXTERNAL_MONITOR_NAME -d 6 7 8 
else
	bspc monitor -d 1 2 3 4 5 
fi
$HOME/.config/polybar/launch.sh
    

# for side in top right bottom left; do bspc config ${side}_monocle_padding -10; done
# Remove top padding in monocle mode
for side in top ; do bspc config ${side}_monocle_padding 0; done
bspc config border_width        4
bspc config window_gap          0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#98c379"
bspc config focused_border_color "#61afef" 
bspc config presel_feedback_color "#bd93f9"
# bspc config external_rules_command ~/.config/bspwm/external_rules.sh

bspc rule -a Zathura state=gapless_monocle 
bspc rule -a SummertimeSaga desktop='^4' state=gapless_monocle 
bspc rule -a "zoom " desktop='^5' state=floating
bspc rule -a Godot state=floating
bspc rule -a Gimp-2.10 desktop='^4' state=gapless_monocle follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a virtualbox desktop='^3' follow=on
bspc rule -a rofi state=floating
bspc rule -a Xfce4-appfinder state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Virt-manager desktop='^3' state=gapless_monocle follow=on
